package protocol

var APIVersions = []APIVersion{
	{APIKey: MetadataKey, MinVersion: 4, MaxVersion: 4}, // Locked to version 4
	{APIKey: OffsetsKey, MinVersion: 0, MaxVersion: 0},  // Locked to version 0

	{APIKey: ProduceKey, MinVersion: 0, MaxVersion: 5},
	{APIKey: FetchKey, MinVersion: 0, MaxVersion: 3},

	{APIKey: LeaderAndISRKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: StopReplicaKey, MinVersion: 0, MaxVersion: 0},
	{APIKey: FindCoordinatorKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: JoinGroupKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: HeartbeatKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: LeaveGroupKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: SyncGroupKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: DescribeGroupsKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: ListGroupsKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: APIVersionsKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: CreateTopicsKey, MinVersion: 0, MaxVersion: 1},
	{APIKey: DeleteTopicsKey, MinVersion: 0, MaxVersion: 1},
}

// return &protocol.APIVersionsResponse{APIVersions: []protocol.APIVersion{
// 	{APIKey: protocol.ProduceKey, MinVersion: 0, MaxVersion: 5},
// 	{APIKey: protocol.FetchKey, MinVersion: 0, MaxVersion: 3},
// 	{APIKey: protocol.OffsetsKey, MinVersion: 0, MaxVersion: 2},
// 	{APIKey: protocol.MetadataKey, MinVersion: 0, MaxVersion: 1}, // Was 1
// 	{APIKey: protocol.LeaderAndISRKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.StopReplicaKey, MinVersion: 0, MaxVersion: 0},
// 	{APIKey: protocol.FindCoordinatorKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.JoinGroupKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.HeartbeatKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.LeaveGroupKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.SyncGroupKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.DescribeGroupsKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.ListGroupsKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.APIVersionsKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.CreateTopicsKey, MinVersion: 0, MaxVersion: 1},
// 	{APIKey: protocol.DeleteTopicsKey, MinVersion: 0, MaxVersion: 1},
// }}
// return &protocol.APIVersionsResponse{
// 	APIVersions: []protocol.APIVersion{
// 		{APIKey: protocol.ProduceKey, MinVersion: 0, MaxVersion: 9},
// 		{APIKey: protocol.FetchKey, MinVersion: 0, MaxVersion: 12},
// 		{APIKey: protocol.OffsetsKey, MinVersion: 0, MaxVersion: 7},
// 		{APIKey: protocol.MetadataKey, MinVersion: 0, MaxVersion: 4}, // Was 11?!
// 		{APIKey: protocol.LeaderAndISRKey, MinVersion: 0, MaxVersion: 5},
// 		{APIKey: protocol.StopReplicaKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.UpdateMetadataKey, MinVersion: 0, MaxVersion: 7},
// 		{APIKey: protocol.ControlledShutdownKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.OffsetCommitKey, MinVersion: 0, MaxVersion: 8},
// 		{APIKey: protocol.OffsetFetchKey, MinVersion: 0, MaxVersion: 8},
// 		{APIKey: protocol.FindCoordinatorKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.JoinGroupKey, MinVersion: 0, MaxVersion: 7},
// 		{APIKey: protocol.HeartbeatKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.LeaveGroupKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.SyncGroupKey, MinVersion: 0, MaxVersion: 5},
// 		{APIKey: protocol.DescribeGroupsKey, MinVersion: 0, MaxVersion: 5},
// 		{APIKey: protocol.ListGroupsKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.SaslHandshakeKey, MinVersion: 0, MaxVersion: 1},
// 		{APIKey: protocol.APIVersionsKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.CreateTopicsKey, MinVersion: 0, MaxVersion: 7},
// 		{APIKey: protocol.DeleteTopicsKey, MinVersion: 0, MaxVersion: 6},
// 		{APIKey: protocol.DeleteRecordsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.InitProducerIDKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.OffsetForLeaderEpochKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.AddPartitionsToTxnKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.AddOffsetsToTxnKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.EndTxnKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.WriteTxnMarkersKey, MinVersion: 0, MaxVersion: 1},
// 		{APIKey: protocol.TxnOffsetCommitKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.DescribeAclsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.CreateAclsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.DeleteAclsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.DescribeConfigsKey, MinVersion: 0, MaxVersion: 4},
// 		{APIKey: protocol.AlterConfigsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.AlterReplicaLogDirsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.DescribeLogDirsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.SaslAuthenticateKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.CreatePartitionsKey, MinVersion: 0, MaxVersion: 3},
// 		{APIKey: protocol.CreateDelegationTokenKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.RenewDelegationTokenKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.ExpireDelegationTokenKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.DescribeDelegationTokenKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: protocol.DeleteGroupsKey, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: 43, MinVersion: 0, MaxVersion: 2},
// 		{APIKey: 44, MinVersion: 0, MaxVersion: 1},
// 		{APIKey: 45, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 46, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 47, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 48, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 49, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 50, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 51, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 56, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 57, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 60, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 61, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 65, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 66, MinVersion: 0, MaxVersion: 0},
// 		{APIKey: 67, MinVersion: 0, MaxVersion: 0},
// 	}}
